server/app/autenticacao/__init__.py
from flask import Blueprint

autenticacao = Blueprint('autenticacao', __name__)

from . import views

server/app/autenticacao/views.py
from flask import render_template, request, redirect, url_for, flash

from . import autenticacao
from .. import db, bcrypt
from ..tabelas import Usuarios, Imagens, Presencas
from ..forms import FormularioLogin, FormularioRegistro
from flask_login import login_user, current_user, logout_user, login_required

"""
    Rotas para registro de usuários
"""
@autenticacao.route('/registrar', methods=['GET'])
def registrar():
    return render_template('autenticacao/registrar.html')

@autenticacao.route('/verificacao_facial')
def verificacao_facial():
    return render_template('autenticacao/verificacao_facial.html')

@autenticacao.route("/criar_conta", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('autenticacao.dashboard'))
    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        ra = request.form['ra']
        senha = request.form['senha']
        perfil = request.form['foto']

        print(f"[{__name__}] Criando Usuaurio: \nNome: {nome}\nEmail: {email} \nRA: {ra}\nSenha: {senha}")
        hashed_password = bcrypt.generate_password_hash(senha).decode('utf-8')
        usuario = Usuarios(nome=nome, email=email, ra=ra, senha=hashed_password)
        usuario_verifica = Usuarios.query.filter_by(email=email).first()
        if usuario_verifica:
            print(f"[{__name__}] Usuário já existe")
            return render_template('autenticacao/registrar.html',  Email='Email já cadastrado!')
        else:
            print(f"{__name__}] Criando Usuario")
            db.session.add(usuario)
            db.session.commit()
            try :
                print(f"[{__name__}] Criando Imagem")
                imagem = Imagens(id_usuario=usuario.id, imagem=perfil)
                db.session.add(imagem)
                db.session.commit()
            except Exception as e:
                print(f"[{__name__}] Erro ao criar imagem: {e}")
                flash("Erro ao cadastrar usuário!", 'error')
            
            flash('Sua conta foi criada com sucesso, faca login para acessar', 'success')
    return redirect(url_for('autenticacao.login'))

"""
    Rotas para login de usuários
"""
@autenticacao.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('autenticacao.dashboard'))
    form = FormularioLogin()
    if form.validate_on_submit():
        user = Usuarios.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.senha, form.password.data):
            login_user(user) # , remember=form.remember.data
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('autenticacao.dashboard'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('autenticacao/login.html', title='Login', form=form)

@autenticacao.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('autenticacao.login'))

@autenticacao.route("/dashboard")
@login_required
def dashboard():
    try:
        total_usuarios = Usuarios.query.count()
        total_presencas = Presencas.query.count()
        total_endpoints = 1
        return render_template('autenticacao/dashboard.html', total_usuarios=total_usuarios, total_presencas=total_presencas, total_endpoints=total_endpoints, title='Dashboard')
    except Exception as e:
        return render_template('autenticacao/dashboard.html', total_usuarios=0, total_presencas=0, total_endpoints=0, title='Dashboard', erro=str(e))

@autenticacao.route("/lista_usuarios")
@login_required
def lista_usuarios():
    usuarios = Usuarios.query.all()
    return render_template('autenticacao/lista_usuarios.html', title='Lista de Usuários', usuarios=usuarios)

@autenticacao.route("/deletar_usuario/<int:id>", methods=['POST'])
@login_required
def deletar_usuario(id):
    user = Usuarios.query.get_or_404(id)
    try:
        # deleta o usuario
        Imagens.query.filter_by(id_usuario=id).delete()
        db.session.delete(user)
        db.session.commit()
        flash('Usuario foi deletado com sucesso!', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao apagar o usuario: {e}', 'danger')
    return redirect(url_for('autenticacao.lista_usuarios'))

@autenticacao.route("/tornar_professor/<int:id>", methods=['POST'])
@login_required
def tornar_professor(id):
    user = Usuarios.query.get_or_404(id)
    user.professor = True
    try:
        db.session.commit()
        flash('O usuário se tornou professor', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao atualizar o usuário: {e}', 'danger')
    return redirect(url_for('autenticacao.lista_usuarios'))

@autenticacao.route("/remover_professor/<int:id>", methods=['POST'])
@login_required
def remover_professor(id):
    user = Usuarios.query.get_or_404(id)
    user.professor = False
    try:
        db.session.commit()
        flash('O usuário deixou de ser professor', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao atualizar o usuário: {e}', 'danger')
    return redirect(url_for('autenticacao.lista_usuarios'))

server/app/presencas/views.py
from flask import render_template, flash, redirect, url_for
import requests
from app import db

from . import presencas
from ..tabelas import Presencas, Usuarios

@presencas.route('/presencas')
def presencas_home():
    status = requests.get('http://localhost:5001/obter_status')
    if status.status_code != 200:
        return render_template('autenticacao/presencas.html', status='Serviço indisponível')
    
    if status.text == '0':
        status = 'Presença não iniciada'
    elif status.text == '1':
        status = 'Presença em andamento'
    else:
        status = 'Erro ao obter status da presença'

    return render_template('autenticacao/presencas.html', status=status)

@presencas.route('/presencas_confirmar/<int:id>', methods=['POST'])
def efetuar_presenca(id):
    return render_template('presencas/efetuar_presenca.html', id=id)

@presencas.route('/presencas_apagar/<int:id>', methods=['POST'])
def apagar_presenca(id):
    try:
        presenca = Presencas.query.get_or_404(id)
        db.session.delete(presenca)
        db.session.commit()
        flash('Presença apagada com sucesso!', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao apagar a presença: {e}', 'danger')
    return redirect(url_for('presencas.historico'))

@presencas.route('/historico')
def historico():
    try:
        presencas = Presencas.query.all()
        for presenca in presencas:
            usuario = Usuarios.query.get(presenca.id_usuario)
            presenca.nome = usuario.nome
            presenca.ra = usuario.ra
        return render_template('presencas/historico.html', presencas=presencas)
    except Exception as e:
        return render_template('presencas/historico.html', presencas=[], erro=str(e))

server/app/templates/autenticacao/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FHO Faltas - {% block title %}{% endblock %}</title>
    <script src="../../static/js/tailwind.js"></script>

    <link rel="shortcut icon" href="../../static/images/favicon.png" type="image/x-icon">
</head>
<body>
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="p-4 font-semibold bg-red-500 text-white alert-{{ category }}">{{ message }}</div>
                    {% endif %}
                    {% if category == 'success' %}
                        <div class="p-4 font-semibold bg-green-500 text-white alert-{{ category }}">{{ message }}</div>
                    {% endif %}
                    {% if category == 'info' %}
                        <div class="p-4 font-semibold bg-green-500 text-white alert-{{ category }}">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

server/app/templates/autenticacao/dashboard.html
{% extends "autenticacao/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div>
    <nav class="bg-white border-b border-gray-200 fixed z-30 w-full">
       <div class="px-3 py-3 lg:px-5 lg:pl-3">
          <div class="flex items-center justify-between">
             <div class="flex items-center justify-start">
                <button id="toggleSidebarMobile" aria-expanded="true" aria-controls="sidebar" class="lg:hidden mr-2 text-gray-600 hover:text-gray-900 cursor-pointer p-2 hover:bg-gray-100 focus:bg-gray-100 focus:ring-2 focus:ring-gray-100 rounded">
                   <svg id="toggleSidebarMobileHamburger" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                   </svg>
                   <svg id="toggleSidebarMobileClose" class="w-6 h-6 hidden" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                   </svg>
                </button>
                <a href="#" class="text-xl font-bold flex items-center lg:ml-2.5">
                  <img src="../../static/images/fho_logo.png" alt="FHO Logo" class="w-16 items-center mr-2">
                  <span class="self-center whitespace-nowrap">FHO Faltas</span>
                </a>
                <form action="#" method="GET" class="hidden lg:block lg:pl-32">
                   <label for="topbar-search" class="sr-only">Pesquisar</label>
                   <div class="mt-1 relative lg:w-64">
                      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                         <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                         </svg>
                      </div>
                      <input type="text" name="email" id="topbar-search" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full pl-10 p-2.5" placeholder="Pesquisar">
                   </div>
                </form>
             </div>
             <div class="flex items-center">
                <button id="toggleSidebarMobileSearch" type="button" class="lg:hidden text-gray-500 hover:text-gray-900 hover:bg-gray-100 p-2 rounded-lg">
                   <span class="sr-only">Pesquisar</span>
                   <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                   </svg>
                </button>
                <div class="hidden lg:flex items-center">
                   <span class="text-base font-normal text-gray-500 mr-5">Logado como <b>{{ current_user.nome }} ✨</b></span>
                </div>
             </div>
          </div>
       </div>
    </nav>
    <div class="flex overflow-hidden bg-white pt-16">
       <aside id="sidebar" class="fixed hidden z-20 h-full top-0 left-0 pt-16 flex lg:flex flex-shrink-0 flex-col w-64 transition-width duration-75" aria-label="Sidebar">
          <div class="relative flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white pt-0">
             <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
                <div class="flex-1 px-3 bg-white divide-y space-y-1">
                   <ul class="space-y-2 pb-2">
                      <li>
                         <form action="#" method="GET" class="lg:hidden">
                            <label for="mobile-search" class="sr-only">Pesquisar</label>
                            <div class="relative">
                               <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                  <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                     <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path>
                                  </svg>
                               </div>
                               <input type="text" name="email" id="mobile-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-cyan-600 focus:ring-cyan-600 block w-full pl-10 p-2.5" placeholder="Search">
                            </div>
                         </form>
                      </li>
                      {% include "autenticacao/dashboard_menu.html" %}
                   </ul>
                </div>
             </div>
          </div>
       </aside>
       <div class="lg:ml-64 p-4 grid grid-cols-3 w-full">
            <div class="w-full p-4">
                <div class="bg-white border border-gray-200 p-6">
                    <h3 class="text-lg font-semibold text-gray-800 flex inline">
                        <svg class="mt-1.5 mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg>
                        Total de Usuarios Cadastrados
                     </h3>
                    <p class="text-3xl font-bold text-gray-700">{{ total_usuarios }}</p>
                </div>
            </div>
        
            <div class="w-full p-4">
                <div class="bg-white border border-gray-200 p-6">
                    <h3 class="text-lg font-semibold text-gray-800">Total de Endpoints Conectados</h3>
                    <p class="text-3xl font-bold text-gray-700">{{ total_endpoints }}</p>
                </div>
            </div>
        
            <div class="w-full p-4">
                <div class="bg-white border border-gray-200 p-6">
                    <h3 class="text-lg font-semibold text-gray-800">Total de Presencas Registradas</h3>
                    <p class="text-3xl font-bold text-gray-700">{{ total_presencas }}</p>
                </div>
            </div>
        </div>

    </div>
 </div>
{% endblock %}

server/app/templates/autenticacao/lista_usuarios.html
{% extends "autenticacao/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div>
    <nav class="bg-white border-b border-gray-200 fixed z-30 w-full">
        <div class="px-3 py-3 lg:px-5 lg:pl-3">
            <div class="flex items-center justify-between">
                <div class="flex items-center justify-start">
                    <button id="toggleSidebarMobile" aria-expanded="true" aria-controls="sidebar" class="lg:hidden mr-2 text-gray-600 hover:text-gray-900 cursor-pointer p-2 hover:bg-gray-100 focus:bg-gray-100 focus:ring-2 focus:ring-gray-100 rounded">
                        <svg id="toggleSidebarMobileHamburger" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                        </svg>
                        <svg id="toggleSidebarMobileClose" class="w-6 h-6 hidden" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
                    <a href="#" class="text-xl font-bold flex items-center lg:ml-2.5">
                        <img src="../../static/images/fho_logo.png" alt="FHO Logo" class="w-16 items-center mr-2">
                        <span class="self-center whitespace-nowrap">FHO Faltas</span>
                    </a>
                    <form action="#" method="GET" class="hidden lg:block lg:pl-32">
                        <label for="topbar-search" class="sr-only">Pesquisar</label>
                        <div class="mt-1 relative lg:w-64">
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                                </svg>
                            </div>
                            <input type="text" name="email" id="topbar-search" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full pl-10 p-2.5" placeholder="Pesquisar">
                        </div>
                    </form>
                </div>
                <div class="flex items-center">
                    <button id="toggleSidebarMobileSearch" type="button" class="lg:hidden text-gray-500 hover:text-gray-900 hover:bg-gray-100 p-2 rounded-lg">
                        <span class="sr-only">Pesquisar</span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
                    <div class="hidden lg:flex items-center">
                        <span class="text-base font-normal text-gray-500 mr-5">Logado como <b>{{ current_user.nome }}</b></span>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="flex overflow-hidden bg-white pt-16">
        <aside id="sidebar" class="fixed hidden z-20 h-full top-0 left-0 pt-16 lg:flex flex-shrink-0 flex-col w-64 transition-width duration-75" aria-label="Sidebar">
            <div class="relative flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white pt-0">
                <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
                    <div class="flex-1 px-3 bg-white divide-y space-y-1">
                        <ul class="space-y-2 pb-2">
                            <li>
                                <form action="#" method="GET" class="lg:hidden">
                                    <label for="mobile-search" class="sr-only">Pesquisar</label>
                                    <div class="relative">
                                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                            <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path>
                                            </svg>
                                        </div>
                                        <input type="text" name="email" id="mobile-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-cyan-600 focus:ring-cyan-600 block w-full pl-10 p-2.5" placeholder="Search">
                                    </div>
                                </form>
                            </li>
                            {% include "autenticacao/dashboard_menu.html" %}
                        </ul>
                    </div>
                </div>
            </div>
        </aside>
        <div class="p-4">
           <div id="main-content" class="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">  
            <main>
            <div class="px-4">
                <h2 class="text-xl font-bold">Listagem de Usuários</h2>
                <p class="text-gray-800">Listagem de todos os usuarios cadastrados no sistema.</p>
                <div class="w-full grid gap-4 pt-2">
                  <table class="min-w-full divide-y divide-gray-200 border-gray-200 border">
                     <thead class="bg-gray-50">
                       <tr>
                         <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nome</th>
                         <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">RA</th>
                         <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                         <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Foto</th>
                         <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Opções</th>
                       </tr>
                     </thead>
                     <tbody class="bg-white divide-y divide-gray-200">
                       {% for usuario in usuarios %}
                       <tr>
                         <td class="px-6 py-4 whitespace-nowrap">{{ usuario.nome }}</td>
                         <td class="px-6 py-4 whitespace-nowrap">{{ usuario.ra }}</td>
                         <td class="px-6 py-4 whitespace-nowrap">{{ usuario.email }}</td>
                         <td class="px-6 py-4 whitespace-nowrap">
                           {% if usuario.imagens %}
                             {% for imagem in usuario.imagens %}
                               <img src="{{ imagem.imagem }}" alt="Foto de {{ usuario.nome }}" class="w-12 h-12 rounded-full">
                             {% endfor %}
                           {% else %}
                             Sem Fotos
                           {% endif %}
                         </td>
                         <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                           <form action="{{ url_for('autenticacao.deletar_usuario', id=usuario.id) }}" method="POST" style="display: inline;">
                             <button type="submit" class="text-red-600 hover:text-red-900" onclick="return confirm('Tem certeza que deseja apagar esse usuario?');">Apagar</button>
                           </form>
                           {% if usuario.professor is none or usuario.professor == 0 %}
                           <form action="{{ url_for('autenticacao.tornar_professor', id=usuario.id) }}" method="POST" style="display: inline;">
                             <button type="submit" class="text-blue-600 hover:text-blue-900 ml-4" onclick="return confirm('Tem certeza que deseja tornar esse usuário professor?');">Tornar Professor</button>
                           </form>
                           {% else %}
                           <form action="{{ url_for('autenticacao.remover_professor', id=usuario.id) }}" method="POST" style="display: inline;">
                             <button type="submit" class="text-red-600 hover:text-red-900 ml-4" onclick="return confirm('Tem certeza que deseja remover esse professor?');">Remover Professor</button>
                           </form>
                           {% endif %}
                         </td>
                       </tr>
                       {% endfor %}
                     </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}